---
apiVersion: v1
kind: Service
metadata:
  name: dov-hsvc
  namespace: dovns
  labels:
    app: dov
    name: dov-svc
spec:
  selector:
    app: dov
    name: dov-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: dov-sts
  namespace: dovns
spec:
  serviceName: dov-hsvc
  replicas: 3
  selector:
    matchLabels:
      app: dov
      name: dov-po
  template:
    metadata:
      labels:
        app: dov
        name: dov-po
    spec:
      containers:
      - name: dov-container
        image: chukmunnlee/dov-bear:v5
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
        ports:
        - containerPort: 3000
        resources: 
          requests: 
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 200m
            memory: 1Gi


