---
apiVersion: v1
kind: Service
metadata:
  name: mysql-hsvc
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  replicas: 2
  serviceName: mysql-hsvc
  selector:
    matchLabels:
      app: mysql
  volumeClaimTemplates:
  - metadata:
    name: data-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        reuqests:
          storage: 1Gi
      storageClassNames: do-block-storage

  template:
    metadata:
      labels: 
        app: mysql
    spec: 
      containers:
      - name: mysql-container
        image: mysql:8
        imagePullPolicy: IfNotPresent
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: changeit
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data-vol
          filePath: /var/lib/sql/
---

  
  