---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bgg-ns
  name: myapp-config
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc
  BGG_DB_PASSWORD: changeit

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bgg-ns
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: bggpod
      namespace: bgg-ns
      labels:
        app: backend
    spec:
      containers:
      - name: bggpod-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: BGG_DB_USER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: BGG_DB_USER
        - name: BGG_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: BGG_DB_HOST
        - name: BGG_DB_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: BGG_DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 1
---

apiVersion: v1
kind: Service

metadata: 
  name: bggapp-svc
  namespace: bgg-ns
spec: 
  type: ClusterIP
  selector: 
    app: backend 
  ports: 
  #service port
  - port: 3000
    targetPort: 3000