---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bgg-ns
  name: bggdb-deploy
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgg-db
  template:
    metadata: 
      name: bgg-db
      namespace: bgg-ns
      labels:
        name: bgg-db
    spec: 
      containers:
      - name: bggdb
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service

metadata: 
  name: bggdb-svc
  namespace: bgg-ns
spec: 
  type: ClusterIP
  selector: 
    name: bgg-db  
  ports: 
  #service port
  - port: 3306
    targetPort: 3306