---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: minio-ns
  name: myapp-config
data:
  MINIO_ROOT_USER: root
  MINIO_ROOT_PASSWORD: password1
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: "minio-sts-0.minio-hsvc.minio-ns.svc.cluster.local,minio-sts-1.minio-hsvc.minio-ns.svc.cluster.local,minio-sts-2.minio-hsvc.minio-ns.svc.cluster.local,minio-sts-3.minio-hsvc.minio-ns.svc.cluster.local"
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
---

apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
spec:
  replicas: 4
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
  volumeClaimTemplates:
  - metadata:
      name: data-vol  # Corrected indentation
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:  # Corrected spelling of 'requests'
          storage: 10Gi
      storageClassName: do-block-storage  # Corrected to 'storageClassName'
  template:
    metadata:
      labels:
        app: minio
        name: minio-po
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: minio-container
        image: bitnami/minio:latest
        env:
        - name: BITNAMI_DEBUG
          value: "true"
        - name: MINIO_ROOT_USER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_DATA_DIR
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_DATA_DIR
        - name: MINIO_DISTRIBUTED_MODE_ENABLED
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_DISTRIBUTED_MODE_ENABLED
        - name: MINIO_DISTRIBUTED_NODES
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_DISTRIBUTED_NODES
        - name: MINIO_API_PORT_NUMBER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_API_PORT_NUMBER
        - name: MINIO_CONSOLE_PORT_NUMBER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: MINIO_CONSOLE_PORT_NUMBER
        ports:
        - name: api-port
          containerPort: 9000
        - name: console-port
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - name: console
    port: 9090
    targetPort: 9090
  - name: data
    port: 9000
    targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-api-ing
spec:
  ingressClassName: nginx
  rules: 
  - host: data.146.190.195.228.nip.io
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: minio-svc
            port: 
              number: 9000
  - host: console.146.190.195.228.nip.io
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: minio-svc
            port: 
              number: 9090
---