---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: default
data: 
  readme.txt:
    hello,world
  values.yaml:
    controller:
      image:
        image: fred/myimage

---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-po
  namespace: default
spec: 
  volumes: 
    # emptyDir: {}
    - name: config-vol
        name: config
  containers:
  - name: mysql-container
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: changeit
    ports:
    - containerPort: 3306
    volumeMounts: 
    - name: data-vol
      mountPath: /var/lib/mysql
    resources: {}
